config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  root to: "main#index"
  get "up" => "rails/health#show", as: :rails_health_check
  get 'mypage', to: 'tasks#mypage'
  resources :tasks
  post "getpoint", to: "tasks#get_point"
  get "signup", to: "signup#new"
  post "signup", to: "signup#create"
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :user_groupes
  has_many :users, through: :user_groupes
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :user_tasks
  has_many :users, through: :user_tasks
end

app/models/user.rb
class User < ApplicationRecord
    has_many :user_tasks
    has_many :tasks, through: :user_tasks
    has_many :user_groups
    has_many :groups, through: :user_groups

    has_secure_password

    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
    validates :user_name, presence: true, length: { minimum: 3 }

    def total_points
        tasks.sum(:points)
    end
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/user_task.rb
class UserTask < ApplicationRecord
  belongs_to :user
  belongs_to :task
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_current_user

    def set_current_user
        if session[:user_id]
            Current.user = User.find_by(id: session[:user_id])
        end
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        @user_data = {}
        User.all.each do |user|
            @user_data[user.user_name] = user.total_points
        end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
      user = User.find_by(email: params[:email])
        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            flash[:success] = "ログインしました。"
            redirect_to root_path
        else
            flash[:now] = "ログイン失敗しました。もう一度試してください。"
            render action: :new, status: :unprocessable_entity
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "ログアウトしました。"
        redirect_to root_path
    end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new
        @user.attributes = params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
        @user.save!
        session[:user_id] = @user.id
        flash[:success] = "アカウントを作成しました。"
        redirect_to root_path

    rescue ActiveRecord::RecordInvalid
        render action: :new, status: :unprocessable_entity
    end

    def user_params
        params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
    end
end

app/controllers/slack_api_controller.rb
class SlackApiController < ActionController::API
  def hello
    client = Slack::Web::Client.new
    client.auth_test
    client.chat_postMessage(channel: '#general', text: 'Hello World', as_user: true)
    client.chat_postMessage(
      channel: '#slackアプリ作成',
      text: 'こんにちは'
    )
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_task, only: [:show, :edit, :update, :destroy]
    def index
      @tasks = Task.all
    end

    def show
    end

    def new
      @task = Task.new
    end

    def edit
    end

    def create
      @task = Task.new(task_params)
      @task.save!
      redirect_to tasks_path
    rescue => e
      flash[:alert] = e.message
      render :new
    end

    def update
      @task.update!(task_params)
      redirect_to tasks_path
    rescue => e
      render :edit
    end

    def destroy
      @task.destroy
      redirect_to tasks_path
    end

    def get_point
      @userTask = UserTask.new
      @userTask.user_id = Current.user.id
      @userTask.task_id = params[:task_id]
      if @userTask.save
        flash[:success] = "ポイントget！"
      end
    end

    def mypage
      current_user = User.find_by(id: session[:user_id])
      if current_user
        @tasks = current_user.tasks
        user = current_user
        @user_data = {}
        @user_data[user.user_name] = user.total_points
        

      else
        flash[:alert] = "ユーザーが見つかりません。"
        redirect_to root_path
      end
    end

    private

    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :points)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/slack_api_helper.rb
module SlackApiHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeamGlasses</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body  class="container">
    <%= render 'shared/header' %>
    <%= render 'shared/message' %>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<% if Current.user %>
  <h1>こんにちは、<%= Current.user.user_name %>さん</h1>
  <%= button_to "ログアウト", logout_path, method: :delete, class: 'btn btn-primary' %>
  <%= link_to 'タスク一覧', tasks_path, class: 'my-2 btn btn-primary' %>
<% end %>

<%= column_chart(@user_data) %>

app/views/shared/_header.html.erb
<header class="container">
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <ul class="navbar-nav ms-auto">
            <% if Current.user %>
                <li class="nav-item" style="display: flex; align-items:center;">
                    <span>アカウント：</span>
                    <%= link_to Current.user.user_name, mypage_path, class: 'nav-link'%>
                    <span>でログイン中</span>
                </li>
                <li class="nav-item">
                    <%= link_to "ログアウト", logout_path, data: { turbo_method: :delete }, class: 'nav-link' %>
                </li>
            <% else %>
                <li class="nav-item">
                    <%= link_to "ログイン", login_path, class: 'nav-link' %>
                </li>
                <li class="nav-item">
                    <%= link_to "新規登録", signup_path, class: 'nav-link' %>
                </li>
            <% end %>
        </ul>
    </nav>
</header>

app/views/shared/_message.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
    <%= value %>
  </div>
<% end %>

app/views/signup/new.html.erb
<%= form_with model: @user, url: signup_path do |form| %>
  <% if form.object.errors.any? %>
    <div class="alert alert-danger">
      <% form.object.errors.full_messages.each do |message|  %>
        <div>
          <%= message %>
        </div>
      <% end  %>
    </div>
  <% end %>
  <div class="form-group">
    <%= form.label :user_name %>
    <%= form.text_field :user_name, placeholder: "Please enter your user name (minimum 3 characters)", class: "form-control mb-3" %>
  </div>
  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, placeholder: "user@example.com", class: "form-control mb-3"  %>
  </div>
  <div class="form-group">
    <%= form.label :password %>
    <%= form.password_field :password, placeholder: "Please enter your password", class: "form-control mb-3"  %>
  </div>
  <div class="form-group">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, placeholder: "Please enter your password again", class: "form-control mb-3"  %>
  </div>
  <%= form.submit "登録", class:'btn btn-primary' %>
<% end %>

app/views/tasks/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with(model: task) do |form| %>
      <% if task.errors.any? %>
        <div id="error_explanation" class="alert alert-danger">
          <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

          <ul>
            <% task.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="mb-3">
        <%= form.label :title, class: 'form-label' %>
        <%= form.text_field :title, id: :task_title, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= form.label :points, class: 'form-label' %>
        <%= form.number_field :points, id: :task_points, class: 'form-control' %>
      </div>

      <div class="actions">
        <%= form.submit 'Save', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/tasks/edit.html.erb
<div class="container mt-4">
  <h1>Edit Task</h1>

  <%= render 'form', task: @task %>

  <%= link_to 'Back', tasks_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/tasks/index.html.erb
<div class="container mt-4">
  <h1>Tasks</h1>
  <%= link_to 'New Task', new_task_path, class: 'btn btn-primary' %>
  <%= link_to 'ポイント確認', root_path, class: 'btn btn-primary' %>

  <table class="table table-striped">
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Points</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= link_to task.title, task, class: 'text-decoration-none' %></td>
          <td><%= task.points %></td>
          <td><%= link_to 'PointGet!', getpoint_path(task_id: task.id), data: {turbo_method: :post}, class: 'btn btn-info' %></td>
          <td><%= link_to 'Edit', edit_task_path(task), class: 'btn btn-secondary' %></td>
          <td><%= link_to 'Destroy', task, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/tasks/mypage.html.erb
<h2>My Page</h2>
<%= column_chart(@user_data) %>
<h6>実行タスク履歴</h6>
<table class="table table-striped">
    <thead class="thead-dark">
        <tr>
            <th>Title</th>
            <th>Points</th>
            <th colspan="3"></th>
        </tr>
    </thead>

    <tbody>
        <% @tasks.each do |task| %>
            <tr>
                <td><%= link_to task.title, task, class: 'text-decoration-none' %></td>
                <td><%= task.points %></td>
                <td><%= link_to 'PointGet!', getpoint_path(task_id: task.id), data: {turbo_method: :post}, class: 'btn btn-info' %></td>
                <td><%= link_to 'Edit', edit_task_path(task), class: 'btn btn-secondary' %></td>
                <td><%= link_to 'Destroy', task, data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: 'btn btn-danger' %></td>
            </tr>
        <% end %>
    </tbody>
</table>

app/views/tasks/new.html.erb
<div class="container mt-4">
  <h1>New Task</h1>

  <%= render 'form', task: @task %>

  <%= link_to 'Back', tasks_path, class: 'btn btn-secondary mt-3' %>
</div>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>

<p>
  Points: <%= @task.points %>
</p>

<%= link_to 'Edit', edit_task_path(@task), class: 'btn btn-primary' %>
<%= link_to 'Back', tasks_path, class: 'btn btn-secondary' %>